name: Maxim Gordienok
favicon: null
layout_spectrum: 0.8629938964731991
typography_spectrum: 0.8017245421651751
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.10543388011865318
  lightness: 0.9967910829000175
  saturation: 0.9795352346263826
  rhythmicContrast: 0.06860335427336395
purpose: []
